### PR TITLE
Edition 2021 update and some slight fixes.

### PR DESCRIPTION
**Pull request by MGlolenstine**
Switched to 2021 feature set.
Fixed lifetime issues in the client.
Satisfied clippy.

### CODE REVIEW

**Comment by JMurph2015** [comment]
Does clippy explicitly care about using explicit `return` statements?  If not, I prefer to keep that particular syntax out of my codebase since it's not as clear as a nice return statement 🙂.

**Comment by MGlolenstine** [comment]
Omitting return statements is considered idiomatic rust and clippy does catch it.
https://rust-lang.github.io/rust-clippy/master/index.html#implicit_return
`CI` for rust repositories often includes `cargo clippy -D warn`, which would return an error.
I don't mind either syntax and if you prefer the return statements, the "pragma" can be insterted at the root of the crate.

**Comment by MGlolenstine** [comment]
Actually my bad, I've linked to the wrong clippy lint.
I meant to send this one. It does report as a warning by default.
https://rust-lang.github.io/rust-clippy/master/index.html#needless_return

**Comment by JMurph2015** [comment]
There's a couple clippy things I will deal with later, for now this can be merged and I'll fix the clippy pragmas for future stuff.

**Review by JMurph2015 — APPROVED** [review]

**Pull request merged**
